### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por su id
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las peliculas por un genero
GET http://localhost:1234/movies?genre=Action

### Crear una película
POST http://localhost:1234/movies
Content-Type: application/json

{
 "id": "241bf55d-b649-4109-af7c-0e6890ded3fc",
  "title": "Sex Machine",
  "year": 1999,
  "director": "Quentin Tarantino",
  "duration": 154,
  "poster": "https://www.themoviedb.org/t/p/original/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
  "genre": ["Crime", "Drama"],
  "rate": 8.9
}  

### Actualizar una pelicula
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "title": "Redemption",
    "year": 1944
}















